const OWNER = "suhaimi-masri-ent";
const REPO = "support";
const ALLOWED_ORIGIN = "https://suhaimi-masri-ent.github.io";
function corsHeaders(origin) { return { "Access-Control-Allow-Origin": origin === ALLOWED_ORIGIN ? origin : ALLOWED_ORIGIN, "Access-Control-Allow-Methods": "GET, POST, OPTIONS", "Access-Control-Allow-Headers": "Content-Type", "Content-Type": "application/json" }; }
function json(data, status, origin) { return new Response(JSON.stringify(data), { status, headers: corsHeaders(origin) }); }
function clean(value, maxLength) { return String(value || "").trim().slice(0, maxLength); }
function parseField(body, label) { const match = String(body || "").match(new RegExp(`\\*\\*${label}:\\*\\*\\s*(.+)`)); return match ? match[1].trim() : ""; }
function publicTicket(issue, engineer) { const solution = String(issue.body || "").match(/## Customer solution\s*([\s\S]*?)(?=\n## |\n---|$)/i); return { number: issue.number, title: issue.title.replace(/^\[[^\]]+\]\s*/, ""), state: issue.state, created_at: issue.created_at, updated_at: issue.updated_at, email: engineer ? parseField(issue.body, "Email") : undefined, phone: engineer ? parseField(issue.body, "Phone") : undefined, solution: solution ? solution[1].trim() : "" }; }
async function github(path, env) { const response = await fetch(`https://api.github.com${path}`, { headers: { Accept: "application/vnd.github+json", Authorization: `Bearer ${env.GITHUB_TOKEN}`, "X-GitHub-Api-Version": "2022-11-28", "User-Agent": "suhaimi-support-desk" } }); return { response, data: await response.json() }; }
async function listTickets(request, env, origin) { const url = new URL(request.url); const engineerKey = clean(url.searchParams.get("engineerKey"), 200); const email = clean(url.searchParams.get("email"), 160).toLowerCase(); const phone = clean(url.searchParams.get("phone"), 40); const engineer = Boolean(engineerKey && env.ENGINEER_ACCESS_KEY && engineerKey === env.ENGINEER_ACCESS_KEY); if (!engineer && (!email || !phone)) return json({ message: "Email and phone number are required." }, 400, origin); if (!engineer && !/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)) return json({ message: "Please provide a valid email address." }, 400, origin); const { response, data } = await github(`/repos/${OWNER}/${REPO}/issues?state=all&per_page=100`, env); if (!response.ok) return json({ message: "Unable to load tickets." }, 502, origin); const tickets = data.filter(issue => !issue.pull_request).filter(issue => engineer || (parseField(issue.body, "Email").toLowerCase() === email && parseField(issue.body, "Phone") === phone)).map(issue => publicTicket(issue, engineer)); return json({ tickets }, 200, origin); }
export default { async fetch(request, env) { const origin = request.headers.get("Origin") || ""; if (request.method === "OPTIONS") return new Response(null, { status: 204, headers: corsHeaders(origin) }); if (request.method === "GET") return listTickets(request, env, origin); if (request.method !== "POST") return json({ message: "Method not allowed." }, 405, origin); try { const data = await request.json(); const requester = clean(data.requester, 100), email = clean(data.email, 160), phone = clean(data.phone, 40), company = clean(data.company, 150), category = clean(data.category, 50), priority = clean(data.priority, 20), summary = clean(data.summary, 180), details = clean(data.details, 10000); if (!requester || !email || !phone || !category || !priority || !summary || !details) return json({ message: "Please complete all required fields, including phone number." }, 400, origin); if (!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)) return json({ message: "Please provide a valid email address." }, 400, origin); const issueBody = `## Requester\n\n**Name:** ${requester}\n\n**Email:** ${email}\n\n**Phone:** ${phone}\n\n**Company:** ${company || "Not provided"}\n\n## Request\n\n**Category:** ${category}\n\n**Priority:** ${priority}\n\n**Summary:** ${summary}\n\n## Problem details\n\n${details}\n\n## Customer solution\n\n_Pending support team update._\n\n---\n_This section is customer-visible. Keep internal discussion in issue comments._`; const { response, data: githubData } = await github(`/repos/${OWNER}/${REPO}/issues`, env, { method: "POST" }); const createResponse = await fetch(`https://api.github.com/repos/${OWNER}/${REPO}/issues`, { method: "POST", headers: { Accept: "application/vnd.github+json", Authorization: `Bearer ${env.GITHUB_TOKEN}`, "X-GitHub-Api-Version": "2022-11-28", "User-Agent": "suhaimi-support-desk", "Content-Type": "application/json" }, body: JSON.stringify({ title: `[${priority}] ${summary}`, body: issueBody, labels: ["support", `priority:${priority.toLowerCase()}`] }) }); const created = await createResponse.json(); if (!createResponse.ok) return json({ message: "GitHub could not create the ticket." }, 502, origin); return json({ success: true, issueNumber: created.number, issueUrl: `${ALLOWED_ORIGIN}/tickets.html` }, 200, origin); } catch (error) { console.error(error); return json({ message: "Unable to process the support request." }, 500, origin); } } };
